{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hamburghini.playerplus",
    "module": "playerplus-analytics",
    "version": "0.0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "playerplus-analytics-0.0.31.aar",
          "url": "playerplus-analytics-0.0.31.aar",
          "size": 26848,
          "sha512": "bed322072d1319eca9775e1b12cdc75dad0905d867abd7621351329e92713a12831b676f71b7a4e02942ebe2c68365366b57373be2e0a61cb1e42e09cf26bb36",
          "sha256": "7eba83ae802002035f68bc7fb8105ec00bd388fb87829f6315d845c848a051be",
          "sha1": "814ce810fc4743e9b6f44e6bf34b9586227fb70f",
          "md5": "85f34c4f9adcde3c877317bbd408a4f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hamburghini.playerplus",
          "module": "playerplus",
          "version": {
            "requires": "0.0.31"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.56.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.56.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-metrics",
          "version": {
            "requires": "1.56.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-trace",
          "version": {
            "requires": "1.56.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs",
          "version": {
            "requires": "1.56.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.56.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-semconv",
          "version": {
            "requires": "1.30.1-alpha"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "playerplus-analytics-0.0.31.aar",
          "url": "playerplus-analytics-0.0.31.aar",
          "size": 26848,
          "sha512": "bed322072d1319eca9775e1b12cdc75dad0905d867abd7621351329e92713a12831b676f71b7a4e02942ebe2c68365366b57373be2e0a61cb1e42e09cf26bb36",
          "sha256": "7eba83ae802002035f68bc7fb8105ec00bd388fb87829f6315d845c848a051be",
          "sha1": "814ce810fc4743e9b6f44e6bf34b9586227fb70f",
          "md5": "85f34c4f9adcde3c877317bbd408a4f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "playerplus-analytics-0.0.31-sources.jar",
          "url": "playerplus-analytics-0.0.31-sources.jar",
          "size": 13421,
          "sha512": "a3f0f4b259821a812c451a174278f359399761f7e69de6b956cd2802f763894633f773ad42e0728557e2a90e12c5cf6b53921efa69db25c11044729259d8f4e9",
          "sha256": "815f0bffefe7ae7a59afa30169878c6dd50503305be3ebf4b2788bae7a85ae20",
          "sha1": "a140d5ae583ce367efd297b6b4fc2424c4663f9f",
          "md5": "d1bf30c982a1e42427867107c6616ec6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "playerplus-analytics-0.0.31-javadoc.jar",
          "url": "playerplus-analytics-0.0.31-javadoc.jar",
          "size": 341704,
          "sha512": "f14c6385418c7c7add6797a013678638a9a0f300bbbd5391f81440cd06ef83a8168d92ee407d979c89693451d43ca2f202668157868b95944308d84a1fa2df31",
          "sha256": "0e7428f49b875f02bcf42d421ab8c2a926ef52bc6d3c5c8b92c90f2d6f73f214",
          "sha1": "3e29fda1614c53ce7b4db67222f32b7532cd9c81",
          "md5": "ab50cee419a772d5f42e16448d272132"
        }
      ]
    }
  ]
}
