{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hamburghini.playerplus",
    "module": "playerplus",
    "version": "0.0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "playerplus-0.0.31.aar",
          "url": "playerplus-0.0.31.aar",
          "size": 105351,
          "sha512": "4e3f936d585d6e0f7500ec63b31cc6f97b08ab41ecd219c860de4a39b08240651b66f095ad70b7e5f8fdea325bb766dd2530177f652fd77016fe9e9fb1616264",
          "sha256": "63ff084267f13bfbc12415d585daff3ddd9344c85676ed61372b22098b507525",
          "sha1": "557ef605d9b9816ec438e629b976b963ae89d3b2",
          "md5": "e2950c1aee3303dc3586c8881b4fe0cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "playerplus-0.0.31.aar",
          "url": "playerplus-0.0.31.aar",
          "size": 105351,
          "sha512": "4e3f936d585d6e0f7500ec63b31cc6f97b08ab41ecd219c860de4a39b08240651b66f095ad70b7e5f8fdea325bb766dd2530177f652fd77016fe9e9fb1616264",
          "sha256": "63ff084267f13bfbc12415d585daff3ddd9344c85676ed61372b22098b507525",
          "sha1": "557ef605d9b9816ec438e629b976b963ae89d3b2",
          "md5": "e2950c1aee3303dc3586c8881b4fe0cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "playerplus-0.0.31-sources.jar",
          "url": "playerplus-0.0.31-sources.jar",
          "size": 53092,
          "sha512": "31316028d1227dd7d88a4e218041cc14cf6e7fdb4ca179f4c2eeac4d56ebbfc1bfd01585b2c647fa1b4d959de9c53dd7679dbea1689fc92c88c8aa5713505857",
          "sha256": "f0485c328664c144e1f99f4a00b7f1cbcbcd1e8af0e5645989dd1b915139517a",
          "sha1": "f811a2b63277cea58adfd016f1ca7c1274f109ef",
          "md5": "d479040ca7c3df23591bc67df49980d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "playerplus-0.0.31-javadoc.jar",
          "url": "playerplus-0.0.31-javadoc.jar",
          "size": 527499,
          "sha512": "669a83f7ba7bc1a2713f635c814f73feddf4ec2d771ce120899f73cb48dbc4195d23010ba9c41271a5cb4cdec71fe233ac8e39e5b962f664acecb654276e3a48",
          "sha256": "59a5dac39ed0068cec962f7c1a9541ea90cd899ee916354cc66c0b5c1cd33b99",
          "sha1": "0c132a959c57eb5421023c0fca8496e68a3ea201",
          "md5": "e2da5120153a240f712568061dae4539"
        }
      ]
    }
  ]
}
